library(data.table)
library(SAIGE)

###Get the BLUP from SAIGE:
prefix='example'
set.seed(h)

fam_all1=read.table(file='example/normalized_pheno.txt',header=T)
covarite.df=read.table(file='example/covariate.txt',header=T)

pheno.blup=as.data.frame(cbind(fam_all1[,c(2:3)],covarite.df[,-c(1,2)]))

fwrite(pheno.blup,file=paste0('example/simu.phenblup.txt'),sep='\t',quote=F,col.names=T,row.names=F)

SAIGE::fitNULLGLMM(plinkFile = "example/example",
                   phenoFile = "example/simu.phenblup.txt",
                   phenoCol = "Y1",
                   traitType = "quantitative",
                   invNormalize = FALSE,
                   covarColList = c("covar1","covar2"),
                   sampleIDColinphenoFile = "IID",
                   outputPrefix = "step1_output",
                   outputPrefix_varRatio = "step1_output_varianceRatio",
                   nThreads=4,
                   IsOverwriteVarianceRatioFile=TRUE)

N=dim(covarite.df)[1]
covariate=as.matrix(cbind(rep(1,N),covarite.df[,-c(1,2)]))

##Load the output file step1_output.rda generated by the SAIGE software using the code provided above.
load("step1_output.rda")

for (chr in c(1:22)){
  lm_covar=covariate%*%as.matrix(modglmm$LOCOResult[[chr]]$coefficients)
  blup.g=modglmm$LOCOResult[[chr]]$linear.predictors-lm_covar
  write.table(blup.g,paste0(path2, '/y.loco_BLUP.saige_chr', chr, '.txt'))
}

###############################
####Perform BLUP.QRS 
get_coveffect<-function(y,cov,tau){
  y=as.matrix(y)
  ltau=length(tau)
  zz = cbind(rep(1, nrow(y)), cov)
  qreg=list()
  for(k in 1:ltau) {
    if ((dim(zz)[2])==1){
      qreg[[k]]=quantile(y, probs = tau[k])
    }else{
      qreg[[k]]= (rq.fit.pfn(zz, y, tau = tau[k]))$coefficients
    }
  }
  return(qreg)
}

## QRank
## reference => https://pubmed.ncbi.nlm.nih.gov/28334222/
## source code => https://CRAN.R-project.org/package=QRank
## Quantile regression
## reference => https://doi.org/10.1201/9781315120256
## source code => https://cran.r-project.org/package=quantreg

QRank_fast <- function(gene, snp, cov = NULL, coveffect,tau = c(0.25, 0.5, 0.75)){
  ltau = length(tau)
  x = as.matrix(snp)
  y = as.matrix(gene)
  if (is.null(cov)==FALSE){
    cov = as.matrix(cov)
  }
  zz = cbind(rep(1, nrow(y)), cov)
  zz=as.matrix(zz)
  VN = matrix(0, nrow = ltau, ncol = ltau)
  for(i in 1:ltau) {
    for(j in 1:ltau) {
      VN[i,j] = min(tau[i], tau[j]) - tau[i] * tau[j]
    }
  }
  xstar = lm(x~zz-1)$residual
  SN = NULL
  qreg=list()
  for(i in 1:ltau) {
    qreg$coefficients=coveffect[[i]]
    #     if ((dim(zz)[2])==1){
    #         qreg=list()
    #         qreg$coefficients=quantile(y, probs = tau[i])
    #         }else{
    #             qreg = rq.fit.pfn(zz, y, tau = tau[i])
    #     }
    qreg$residual = y - zz %*% as.matrix(qreg$coefficients)
    qreg$dual = 1 * (qreg$residual > 0)
    ranks = qreg$dual - (1 - tau[i])
    Sn = as.matrix(t(xstar) %*% (ranks))
    SN = c(SN,Sn)
  }
  
  VN2 = matrix(outer(VN,t(xstar)%*% xstar,"*"), nrow = ltau)
  pvalue1 = pchisq(SN^2/diag(VN2), 1, lower.tail = F)
  names(pvalue1) = tau
  #quantile specific chi-square test statistics
  chi.1=SN^2/diag(VN2)
  
  e = solve(chol(VN2))
  SN2 = t(e) %*% SN
  pvalue = pchisq(sum(SN2^2), ltau, lower.tail = F)
  composite.chi=sum(SN2^2)
  
  result = list(composite.pvalue = pvalue, quantile.specific.pvalue = pvalue1, tau = tau, composite.chi=composite.chi, chi.quantile.specific=chi.1,quantile.specific.beta=SN,quantile.specific.w=(1/diag(VN2)))
  return(result)
}

coveffect=get_coveffect(y_resid.offset1,X_covar,qntl)

y=as.numeric(unlist(fam_all1[,3]))
bim_file=fread('example/example.bim')
M=dim(bim_file)[1]

for (i in c(1:M)) {
  chr <- as.numeric(bim_file[i, 1])
  y_loco.saige=as.matrix(fread(file=paste0('y.loco_BLUP.saige_chr', chr,'.txt'),header=F))[,2]
  y_resid.offset1=y-y_loco.saige
  p.qr3 = QRank_fast(gene = y_resid.offset1,
                     cov = X_covar,
                     snp = geno.chr.scale[, i],
                     coveffect,
                     tau = qntl)
  df.p3 = rbind(df.p3, data.frame(p.qr3$quantile.specific.pvalue %>% t()))
}
colnames(df.p3) = paste0("P QR ", qntl)
df.p3 = df.p3 %>% mutate(`P QR` = apply(X = df.p3, MARGIN = 1, FUN = cauchy.meta), .before = 1)

#df.p3 contains the data with p-values from all quantile levels,
#as well as the composite quantile p-values combined using the Cauchy method.

saveRDS(df.p3, file = 'BLUP.QRS.rds')